//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AbrilBarcodes
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Barcode { get; set; }
        public int Abril_BarcodeSetting { get; set; }
        //public int SettingId { get; set; }
        //[ForeignKey("Abril_BarcodeSetting")]
        public AbrilBarcodesetting AbrilBarcodeSetting { get; set; }
    }
}
