//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AbrilBarcodesetting
    {
        public AbrilBarcodesetting()
        {
            this.AbrilBarcodes = new HashSet<AbrilBarcodes>();
        }
        [Key]
        public int Id { get; set; }
        public string DistrictCode { get; set; }
        public double DistrictId { get; set; }
        public int CurrentNumber { get; set; }
        public virtual ICollection<AbrilBarcodes> AbrilBarcodes { get; set; }
        public int DistrictFK { get; set; }

        [ForeignKey("DistrictFK")]
        public Districts Districts { get; set; }
    }
}
