//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmConfig
    {
        public int Id { get; set; }
        public short CfgType { get; set; }
        public short NumberDocument { get; set; }
        public short DateDocument { get; set; }
        public short AccountNumber { get; set; }
        public short CounterValue { get; set; }
        public short OrgReduced { get; set; }
        public short BillNumber { get; set; }
        public short TelephoneNumber { get; set; }
        public short Barcode { get; set; }
        public short PIB { get; set; }
        public short DateService { get; set; }
        public short Ks { get; set; }
        public short House { get; set; }
        public short Flat { get; set; }
        public short Street { get; set; }
        public short DateStart { get; set; }
        public short DateEnd { get; set; }
        public short Subsidies { get; set; }
        public short ServicePurpose { get; set; }
        public short CounterCode { get; set; }
        public short Period { get; set; }
        public short ServReduced { get; set; }
        public short Additional { get; set; }
    }
}
