//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmFieldConfigs
    {
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int TypeId { get; set; }
        public string ContractNumber { get; set; }
        public string Date_ { get; set; }
        public string SenderAcc { get; set; }
        public string Current_ { get; set; }
        public string Previous_ { get; set; }
        public string Receipt { get; set; }
        public string SenderTelephon { get; set; }
        public string Barcode { get; set; }
        public string SenderFio { get; set; }
        public string DateService { get; set; }
        public string Ks { get; set; }
        public string SenderAdress { get; set; }
        public string DateStart { get; set; }
        public string DateEnd { get; set; }
        public string Subsidies { get; set; }
        public string ServicePurpose { get; set; }
        public string CounterCode { get; set; }
        public string Jek { get; set; }
        public string PayersCheck { get; set; }
        public int OrganisationFK { get; set; }
        public int DesriptionFK { get; set; }
        [ForeignKey("DesriptionFK")]
        public  DescriptionIds DescriptionIds { get; set; }
        [ForeignKey("OrganisationFK")]
        public  Organisations Organisations { get; set; }
        public virtual ServGroup ServGroup { get; set; }
    }
}
