//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public double Id { get; set; }
        public double StreetId { get; set; }
        public string Number { get; set; }
        public string Korpus { get; set; }
    
        public virtual Streets Streets { get; set; }
    }
}
