//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counters
    {
        public int Id { get; set; }
        public int Pl_AccountId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Code { get; set; }
        public string InvCode { get; set; }
        public Nullable<double> Previous_Data { get; set; }
        public Nullable<System.DateTime> Date_Of_Data { get; set; }
    }
}
