//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ExtServiceUser
    {
        public ExtServiceUser()
        {
            this.ExtuserToOlbpUser = new HashSet<ExtUserToOlbpUser>();
        }
        [Key]
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> ExtServId { get; set; }

        public virtual ExternalService ExternalService { get; set; }
        public virtual Organisations Organisations { get; set; }
        public virtual ICollection<ExtUserToOlbpUser> ExtuserToOlbpUser { get; set; }
    }
}
