//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtUserToOlbpUser
    {
        public int Id { get; set; }
        public string OlbpPkId { get; set; }
        public Nullable<int> ExtUserId { get; set; }
    
        public virtual ExtServiceUser ExtServiceUser { get; set; }
        public virtual Users Users { get; set; }
    }
}
