//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceSetttings
    {
        public FinanceSetttings()
        {
            this.Users = new HashSet<Users>();
            this.Plats = new HashSet<Plats>();
        }
        [Key]
        public int Id { get; set; }
        public string DSN { get; set; }
        public long OwnerAccount { get; set; }
        public int ImportType { get; set; }
        public string CPZNumber { get; set; }
    
        public virtual DescriptionIds DescriptionIds { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Plats> Plats { get; set; }
    }
}
