//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Indexes
    {
        public Indexes()
        {
            this.PlCity = new HashSet<PlCity>();
            this.Terminals = new HashSet<Terminals>();
            this.UserToIndex = new HashSet<UserToIndex>();
        }
        [Key]
        public int Id { get; set; }
        public string IndexValue { get; set; }
        public double CityId { get; set; }
        public string NameVz { get; set; }
        public string Code { get; set; }
        public Nullable<int> CpzId { get; set; }
        public Nullable<System.DateTime> LockDate { get; set; }
        public string LockingUser { get; set; }
        public Nullable<System.DateTime> LockingDate { get; set; }

        public virtual ICollection<PlCity> PlCity { get; set; }
        public virtual PlCity PlCity1 { get; set; }
        public virtual ICollection<Terminals> Terminals { get; set; }
        public virtual ICollection<UserToIndex> UserToIndex { get; set; }
    }
}
