//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPaymentsTmp
    {
        public Nullable<int> Id { get; set; }
        public string UserPkId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<double> PaymentSum { get; set; }
        public string PaymObj { get; set; }
    }
}
