//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Organisations
    {
        public Organisations()
        {
            //this.ArmFieldConfigs = new HashSet<ArmFieldConfigs>();
            //    this.ExtServiceUser = new HashSet<ExtServiceUser>();
            //    this.FilesStats = new HashSet<FilesStats>();
            //    this.LocalisationToCity = new HashSet<LocalisationToCity>();
            //    this.organisations1 = new HashSet<Organisations>();
            //    this.PlannerConfigs = new HashSet<PlannerConfigs>();
            //    this.PlannerLog = new HashSet<PlannerLog>();
            //    this.Reestrs = new HashSet<Reestrs>();
            //    this.Services = new HashSet<Services>();
            //    this.OrgToCity = new HashSet<OrgToCity>();
            //    this.PaymentBarcodes = new HashSet<PaymentBarcodes>();
            //    this.Plats = new HashSet<Plats>();
            //    this.PlatTemplates = new HashSet<PlatTemplates>();
            //    this.PlatsTmp = new HashSet<PlatsTmp>();
            //    this.RpayerLinks = new HashSet<RpayerLinks>();
            //    this.ServGroupLinks = new HashSet<ServGroupLinks>();
            //    this.UserToSpeedCodes = new HashSet<UserToSpeedCodes>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Nomenklature { get; set; }
        public string Edrpou { get; set; }
        public string Account { get; set; }
        public string Mfo { get; set; }
        public string Bankname { get; set; }
        public short Tarif { get; set; }
        public double Percent { get; set; }
        public double Minsum { get; set; }
        public Nullable<short> Enabled { get; set; }
        public Nullable<double> CityId { get; set; }
        public string UserId { get; set; }
        public bool Unconfirmed { get; set; }
        public string Contract_Num { get; set; }
        public Nullable<System.DateTime> Contract_Date { get; set; }
        public int ResendType { get; set; }
        public Nullable<bool> CanSavePayer { get; set; }
        public Nullable<bool> CanSaveAccount { get; set; }
        public string FileFolder { get; set; }
        public Nullable<bool> ExportEveryday { get; set; }
        public Nullable<bool> IsMounthProfit { get; set; }
        public bool IsArchive { get; set; }
        public string ReceiverGroup { get; set; }
        public int PayersCheck { get; set; }
        public Nullable<bool> IsUsedGeneralTemplate { get; set; }
        public Nullable<System.DateTime> LockedTime { get; set; }
        public string Additional { get; set; }
        public short UseAdditionalyService { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Use_AutoDefaults { get; set; }
        public int ReducedTypeId { get; set; }
        public int Visibility { get; set; }
        public int LocationId { get; set; }
        public int ReceivingTypeId { get; set; }
        public int WebserviceId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string NomenklatureComission { get; set; }
        public int ExtServiceId { get; set; }

        // public virtual ICollection<ArmFieldConfigs> ArmFieldConfigs { get; set; }
        //public virtual ArmFieldNames ArmFieldNames { get; set; }
        //public virtual DescriptionIds description_ids { get; set; }
        //public virtual DescriptionIds description_ids1 { get; set; }
        //public virtual DescriptionIds description_ids2 { get; set; }
        //public virtual DescriptionIds description_ids3 { get; set; }
        //public virtual DescriptionIds DescriptionIds { get; set; }
        //public virtual ICollection<ExtServiceUser> ExtServiceUser { get; set; }
        //public virtual ICollection<FilesStats> FilesStats { get; set; }
        //public virtual ICollection<LocalisationToCity> LocalisationToCity { get; set; }
        //public virtual ICollection<Organisations> organisations1 { get; set; }
        //public virtual Organisations organisations2 { get; set; }
        //public virtual ICollection<PlannerConfigs> PlannerConfigs { get; set; }
        //public virtual ICollection<PlannerLog> PlannerLog { get; set; }
        //public virtual ReestrsTemplates ReestrsTemplates { get; set; }
        //public virtual ICollection<Reestrs> Reestrs { get; set; }
        //public virtual ResendType Resendtype1 { get; set; }
        //public virtual ICollection<Services> Services { get; set; }
        //public virtual ICollection<OrgToCity> OrgToCity { get; set; }
        //public virtual ICollection<PaymentBarcodes> PaymentBarcodes { get; set; }
        //public virtual ICollection<Plats> Plats { get; set; }
        //public virtual ICollection<PlatTemplates> PlatTemplates { get; set; }
        //public virtual ICollection<PlatsTmp> PlatsTmp { get; set; }
        //public virtual ICollection<RpayerLinks> RpayerLinks { get; set; }
        //public virtual ICollection<ServGroupLinks> ServGroupLinks { get; set; }
        //public virtual Tarifs Tarifs { get; set; }
        //public virtual ICollection<UserToSpeedCodes> UserToSpeedCodes { get; set; }
    }
}
