//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgToCity
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public double CityId { get; set; }

        public virtual Organisations Organisations { get; set; }
        public virtual PlCity PlCity { get; set; }
    }
}
