//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBarcodes
    {
        public int Id { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public int FieldId { get; set; }
        public int StartFrom { get; set; }
        public int Length { get; set; }
        public Nullable<int> Scale { get; set; }
        public string Splitter { get; set; }
    
        public virtual DescriptionIds DescriptionIds { get; set; }
        public virtual Organisations Organisations { get; set; }
        public virtual Services Services { get; set; }
    }
}
