//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsTmp
    {
        public int Id { get; set; }
        public string indexvz { get; set; }
        public string operatorfio { get; set; }
        public Nullable<int> oper_wnd_number { get; set; }
        public string payment_code { get; set; }
        public Nullable<double> payment_sum { get; set; }
        public Nullable<double> comission_sum { get; set; }
        public Nullable<double> bonus_sum { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> receiverid { get; set; }
        public string receiveredrpou { get; set; }
        public string receivername { get; set; }
        public string receiveracc { get; set; }
        public string receivermfo { get; set; }
        public string receiverbnkname { get; set; }
        public string senderacc { get; set; }
        public string senderfio { get; set; }
        public string senderadress { get; set; }
        public string senderpass { get; set; }
        public string sendertel { get; set; }
        public string contractnumber { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<int> ks { get; set; }
        public Nullable<double> previous_ { get; set; }
        public Nullable<double> current_ { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string jek { get; set; }
        public string service_name { get; set; }
        public string barcode { get; set; }
        public Nullable<int> operatorid { get; set; }
        public string namevz { get; set; }
        public string sessionid { get; set; }
        public string nomenklature { get; set; }
        public Nullable<int> paymenttype { get; set; }
        public Nullable<System.DateTime> export_date { get; set; }
        public string export_login { get; set; }
        public Nullable<System.DateTime> exp_date_to_file { get; set; }
        public string exp_to_file_login { get; set; }
        public Nullable<System.DateTime> date_service { get; set; }
        public Nullable<System.DateTime> offlineimportdate { get; set; }
        public string receipt { get; set; }
        public Nullable<int> plat_num { get; set; }
        public string sendercity { get; set; }
        public string senderbuilding { get; set; }
        public string senderkorpus { get; set; }
        public string senderapartment { get; set; }
        public Nullable<double> resend_sum { get; set; }
        public Nullable<int> resend_type { get; set; }
        public Nullable<bool> payment_type { get; set; }
        public Nullable<double> debt { get; set; }
        public Nullable<double> addsum { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string edit_login { get; set; }
        public string additionally { get; set; }
        public Nullable<bool> cpzimport { get; set; }
        public Nullable<int> mdaddvalueid { get; set; }
        public Nullable<int> senderid { get; set; }
        public string identifier { get; set; }
        public string receivergroup { get; set; }
        public Nullable<int> fileid { get; set; }
        public string service_purpose { get; set; }
        public Nullable<double> subsidies { get; set; }
        public Nullable<System.DateTime> plat_date { get; set; }
        public string counter_code { get; set; }
        public string service_code { get; set; }
        public Nullable<double> sendercityid { get; set; }
        public Nullable<int> group_sign { get; set; }
        public string plat_edrpou { get; set; }
        public string plat_mfo { get; set; }
        public string plat_acc { get; set; }
    }
}
