//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Payments
    {
        public int Id { get; set; }
        public string IndexVz { get; set; }
        public string OperatorFio { get; set; }
        public Nullable<int> OperWndNumber { get; set; }
        public string PaymentCode { get; set; }
        public Nullable<double> PaymentSum { get; set; }
        public Nullable<double> ComissionSum { get; set; }
        public Nullable<double> BonusSum { get; set; }
        public int StatusId { get; set; }
        public int ReceiverId { get; set; }
        public string ReceiverEdrpou { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverAcc { get; set; }
        public string ReceiverMfo { get; set; }
        public string ReceiverBnkName { get; set; }
        public string SenderAcc { get; set; }
        public string SenderFio { get; set; }
        public string SenderAdress { get; set; }
        public string SenderPass { get; set; }
        public string SenderTel { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public int Period { get; set; }
        public Nullable<int> Ks { get; set; }
        public Nullable<double> Previous_ { get; set; }
        public Nullable<double> Current_ { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public string Jek { get; set; }
        public string Service_Name { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string NameVz { get; set; }
        public string SessionId { get; set; }
        public string Nomenklature { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ExportLogin { get; set; }
        public Nullable<System.DateTime> ExpDateToFile { get; set; }
        public string ExpToFileLogin { get; set; }
        public Nullable<System.DateTime> DateService { get; set; }
        public Nullable<System.DateTime> OflineImportDate { get; set; }
        public string Receipt { get; set; }
        public int PlatNum { get; set; }
        public string SenderCity { get; set; }
        public string SenderBuilding { get; set; }
        public string SenderKorpus { get; set; }
        public string SenderApartment { get; set; }
        public Nullable<double> ResendSum { get; set; }
        public Nullable<int> ResendType { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> AddSum { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditLogin { get; set; }
        public string Additionally { get; set; }
        public Nullable<bool> CpzImport { get; set; }
        public Nullable<int> MdAddValueId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public string Identifier { get; set; }
        public string ReceiverGroup { get; set; }
        public Nullable<int> FileId { get; set; }
        public string ServicePurpose { get; set; }
        public Nullable<double> Subsidies { get; set; }
        public Nullable<System.DateTime> PlatDate { get; set; }
        public string CounterCode { get; set; }
        public string ServiceCode { get; set; }
        public Nullable<double> SenderCityId { get; set; }
        public Nullable<int> GroupSign { get; set; }
        public string PlatEdrpou { get; set; }
        public string PlatMfo { get; set; }
        public string PlatAcc { get; set; }
    }
}
