//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlAccounts
    {
        public int Id { get; set; }
        public Nullable<int> PayerId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string Account { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> AddSum { get; set; }
        public Nullable<double> Subsidies { get; set; }
        public string ComentDebt { get; set; }
        public string ComentAddSum { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Login { get; set; }
        public string Additionally { get; set; }
        public Nullable<decimal> Straf { get; set; }
        public Nullable<int> ServiceId { get; set; }
    }
}
