//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannerConfigs
    {
        public int Id { get; set; }
        public Nullable<int> org_id { get; set; }
        public int action_id { get; set; }
        public int period_id { get; set; }
        public System.DateTime action_time { get; set; }
        public System.DateTime last_action_time { get; set; }
        public short last_action_result { get; set; }
    
        public virtual DescriptionIds description_ids { get; set; }
        public virtual DescriptionIds description_ids1 { get; set; }
        public virtual Organisations organisations { get; set; }
    }
}
