//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plats
    {
        public Plats()
        {
            this.Reestrs = new HashSet<Reestrs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DatePlat { get; set; }
        public string Payer { get; set; }
        public string PayerBank { get; set; }
        public string PayerEdrpou { get; set; }
        public string PayerMfo { get; set; }
        public string PayerAccount { get; set; }
        public decimal SumPlat { get; set; }
        public string Adressee { get; set; }
        public int AdresseeId { get; set; }
        public string AdresseeEdrpou { get; set; }
        public string AdresseeMfo { get; set; }
        public string AdresseeAccount { get; set; }
        public string AdresseeBank { get; set; }
        public short State { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }
        public string UserPkId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string MppzDsn { get; set; }
        public Nullable<int> SapFileId { get; set; }
        public System.DateTime PaymentMinDate { get; set; }
        public System.DateTime PaymentMaxDate { get; set; }
    
        public virtual FilesStats FilesStats { get; set; }
        public virtual FinanceSetttings FinanceSetttings { get; set; }
        public virtual Organisations Organisations { get; set; }
        public virtual ICollection<Reestrs> Reestrs { get; set; }
    }
}
