//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatTemplates
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public string ContentTemplate { get; set; }
        public string GroupByCodes { get; set; }
        public Nullable<short> TemplateType { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Organisations Organisations { get; set; }
        public virtual Services Services { get; set; }
    }
}
