//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatsTmp
    {
        public int Id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.DateTime> date_plat { get; set; }
        public string payer { get; set; }
        public string payer_bank { get; set; }
        public string payer_edrpou { get; set; }
        public string payer_mfo { get; set; }
        public string payer_account { get; set; }
        public decimal sum_plat { get; set; }
        public string adressee { get; set; }
        public int adressee_id { get; set; }
        public string adressee_edrpou { get; set; }
        public string adressee_mfo { get; set; }
        public string adressee_account { get; set; }
        public string adressee_bank { get; set; }
        public short state { get; set; }
        public string content { get; set; }
        public string username { get; set; }
        public string user_pkid { get; set; }
        public System.DateTime date_create { get; set; }
        public string mppz_dsn { get; set; }
        public System.DateTime payment_min_date { get; set; }
        public System.DateTime payment_max_date { get; set; }
    
        public virtual Organisations organisations { get; set; }
    }
}
