//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PlCity
    {
        public PlCity()
        {
            this.indexes1 = new HashSet<Indexes>();
            this.localisation_to_city = new HashSet<LocalisationToCity>();
            this.org_to_city = new HashSet<OrgToCity>();
            this.services_to_city = new HashSet<ServicesToCity>();
            this.streets = new HashSet<Streets>();
        }
        [Key]
        public int Id { get; set; }
        public double cityid { get; set; }
        public Nullable<double> regionid { get; set; }
        public string cityname { get; set; }
        public double districtid { get; set; }
        public bool districtcenter { get; set; }
        public string geo_code { get; set; }
        public string phone_code { get; set; }
        public Nullable<int> IndexId { get; set; }
        public int DistrictFK { get; set; }
        public int IndexesFK { get; set; }
        public Nullable<int> orgidfl { get; set; }
        //[ForeignKey("DistrictFK")]
        public Districts Districts { get; set; }
       
        //[ForeignKey("IndexesFK")]
        public Indexes indexes { get; set; }
        public virtual ICollection<Indexes> indexes1 { get; set; }
        public virtual ICollection<LocalisationToCity> localisation_to_city { get; set; }
        public virtual ICollection<OrgToCity> org_to_city { get; set; }
        public virtual ICollection<ServicesToCity> services_to_city { get; set; }
        public virtual ICollection<Streets> streets { get; set; }
    }
}
