//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reestrs
    {
        public Reestrs()
        {
            this.files_stats = new HashSet<FilesStats>();
        }
    
        public int id { get; set; }
        public int org_id { get; set; }
        public int number { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> plat_id { get; set; }
        public decimal payment_sum { get; set; }
        public int payment_count { get; set; }
        public string user_pkid { get; set; }
        public int isarchive { get; set; }
        public System.DateTime payment_min_date { get; set; }
        public System.DateTime payment_max_date { get; set; }
    
        public virtual ICollection<FilesStats> files_stats { get; set; }
        public virtual Organisations organisations { get; set; }
        public virtual Plats plats { get; set; }
    }
}
