//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regions
    {
        public Regions()
        {
            this.Districts = new HashSet<Districts>();
        }

        public int Id { get; set; }
        public double RegionId { get; set; }
        public string RegionName { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Districts> Districts { get; set; }
    }
}
