//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDefaults
    {
        public int Id { get; set; }
        public int report_type { get; set; }
        public short organisation { get; set; }
        public short service { get; set; }
        public short index { get; set; }
        public short localisation { get; set; }
        public short servgroup { get; set; }
        public short iscanceled { get; set; }
        public short isusedgeneraltemplate { get; set; }
        public short operatorfio { get; set; }
        public short export_date { get; set; }
        public short period { get; set; }
        public short plat_num { get; set; }
        public short recever_account { get; set; }
        public short service_tarif { get; set; }
        public string user_pkid { get; set; }
    
        public virtual DescriptionIds description_ids { get; set; }
        public virtual Users users { get; set; }
    }
}
