//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpayerLinks
    {
        public int id { get; set; }
        public int rpayerid { get; set; }
        public int orgid { get; set; }
        public string account { get; set; }
        public Nullable<int> service_id { get; set; }
        public string operator_fio { get; set; }
        public string indexvz { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
    
        public virtual Organisations organisations { get; set; }
        public virtual ReducedPayers reduced_payers { get; set; }
        public virtual Services services { get; set; }
    }
}
