//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesToCity
    {
        public int id { get; set; }
        public int service_id { get; set; }
        public double city_id { get; set; }
    
        public virtual PlCity pl_city { get; set; }
        public virtual Services services { get; set; }
    }
}
