//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ServGroup
    {
        public ServGroup()
        {
            // this.ArmFieldConfigs = new HashSet<ArmFieldConfigs>();
            servgroup_links = new HashSet<ServGroupLinks>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public bool print_all_rekv { get; set; }
        public string nomenklature_comission { get; set; }

        public virtual ICollection<ServGroupLinks> servgroup_links { get; set; }
    }
}
