//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServGroupLinks
    {
        public int id { get; set; }
        public Nullable<int> orgid { get; set; }
        public Nullable<int> servgroupid { get; set; }
    
        public virtual Organisations organisations { get; set; }
        public virtual ServGroup ServGroup { get; set; }
    }
}
