//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifs
    {
        public Tarifs()
        {
            this.Organisations = new HashSet<Organisations>();
            this.Services = new HashSet<Services>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Organisations> Organisations { get; set; }
        public virtual ICollection<Services> Services { get; set; }
    }
}
