//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateFields
    {
        public TemplateFields()
        {
            this.TempFieldToFunc = new HashSet<TempFieldToFunc>();
        }
    
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public int dbFieldId { get; set; }
        public string FieldAlias { get; set; }
        public string FileFieldName { get; set; }
        public string FileFieldType { get; set; }
        public string FileFieldFormat { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> FieldOrder { get; set; }
    
        public virtual ICollection<TempFieldToFunc> TempFieldToFunc { get; set; }
        public virtual TemplateFieldAliases TemplateFieldAliases { get; set; }
        public virtual Templates templates { get; set; }
    }
}
