//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templates
    {
        public Templates()
        {
            this.template_fields = new HashSet<TemplateFields>();
        }
    
        public int id { get; set; }
        public int orgid { get; set; }
        public Nullable<int> template_type { get; set; }
        public string name { get; set; }
        public int code_page { get; set; }
        public Nullable<int> template_state { get; set; }
        public string file_type { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string file_name { get; set; }
        public string separator { get; set; }
        public int numeration_type { get; set; }
        public short with_header { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<short> actual { get; set; }
        public short isupdate { get; set; }
    
        public virtual Services services { get; set; }
        public virtual ICollection<TemplateFields> template_fields { get; set; }
        public virtual TemplatesType templates_type { get; set; }
    }
}
