//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesType
    {
        public TemplatesType()
        {
            this.templates = new HashSet<Templates>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string export_import { get; set; }
    
        public virtual ICollection<Templates> templates { get; set; }
    }
}
