//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempFieldToFunc
    {
        public int Id { get; set; }
        public int FieldId { get; set; }
        public int FuncId { get; set; }
        public int FuncOrder { get; set; }
        public string Argument { get; set; }
    
        public virtual TemplateFields TemplateFields { get; set; }
        public virtual TemplateFunc TemplateFunc { get; set; }
    }
}
