//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateFieldAliases
    {
        public TemplateFieldAliases()
        {
            this.TemplateFields = new HashSet<TemplateFields>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public Nullable<short> IsMoney { get; set; }
        public string FieldAlias { get; set; }
        public string DefaultValue { get; set; }
        public string FieldFormat { get; set; }
        public Nullable<int> TemplateType { get; set; }
    
        public virtual ICollection<TemplateFields> TemplateFields { get; set; }
    }
}
