//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateFunc
    {
        public TemplateFunc()
        {
            this.TempFieldToFunc = new HashSet<TempFieldToFunc>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string alias_type { get; set; }
        public Nullable<short> argument_count { get; set; }
        public string func_type { get; set; }
        public string result_type { get; set; }

        public virtual ICollection<TempFieldToFunc> TempFieldToFunc { get; set; }
    }
}
